"""Add datetime expr and change code at phonecode table

Revision ID: 122d667ff767
Revises: 2135ac7673a0
Create Date: 2022-05-01 20:24:48.114150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122d667ff767'
down_revision = '2135ac7673a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonecode', sa.Column('expr_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phonecode', 'expr_date')
    # ### end Alembic commands ###
