"""Added required tables

Revision ID: 248fdb475a35
Revises: 374bcaa0eb50
Create Date: 2022-04-15 00:19:04.941810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248fdb475a35'
down_revision = '374bcaa0eb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
