"""Added required tables

Revision ID: 4a0a5ed64926
Revises: a14f7e8d03e5
Create Date: 2022-04-15 00:38:57.362603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0a5ed64926'
down_revision = 'a14f7e8d03e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
