"""Added required tables

Revision ID: a14f7e8d03e5
Revises: cef68dfedb15
Create Date: 2022-04-15 00:35:13.121789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14f7e8d03e5'
down_revision = 'cef68dfedb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
