"""Add token field

Revision ID: c001ca2acf06
Revises: e7ecc87f56eb
Create Date: 2022-05-01 20:47:51.724679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c001ca2acf06'
down_revision = 'e7ecc87f56eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonecode', sa.Column('code_auth', sa.String(length=60), nullable=True))
    op.drop_column('phonecode', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonecode', sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_column('phonecode', 'code_auth')
    # ### end Alembic commands ###
