"""Added required tables

Revision ID: cef68dfedb15
Revises: 248fdb475a35
Create Date: 2022-04-15 00:20:16.829693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef68dfedb15'
down_revision = '248fdb475a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonecode',
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonecode')
    # ### end Alembic commands ###
