"""Add token field

Revision ID: e7ecc87f56eb
Revises: 122d667ff767
Create Date: 2022-05-01 20:27:57.612667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ecc87f56eb'
down_revision = '122d667ff767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonecode', sa.Column('token', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phonecode', 'token')
    # ### end Alembic commands ###
